config/routes.rb
Rails.application.routes.draw do
  resources :blogs

  root 'blogs#index'

  get 'blogs' => 'blogs#index'

  get 'draft' => 'blogs#draft'

  get 'trash' => 'blogs#trash'

  get 'draft-edit' => 'blogs#draft_edit'

end

app/models/blog.rb
class Blog < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:edit, :update, :destroy]

  def index
    @blog = Blog.where(status: '2')
  end

  def show
  end

  def new
    @blog = Blog.new
  end

  def create
    Blog.create(blogs_params)
    redirect_to blogs_path
  end

  def edit
  end

  def update
    @blog.update(blogs_params)
    redirect_to blogs_path
  end

  def destroy
    @blog.update(status: 3)
    redirect_to blogs_path
  end

  def draft
    @blog = Blog.where(status: '1')
  end

  def trash
    @blog = Blog.where(status: '3')
  end

  private
    def blogs_params
      params.require(:blog).permit(:title, :content, :status)
    end

    def set_blog
      @blog = Blog.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_form.html.erb
<%= form_for(@blog) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, class: 'form-control' %>
  <br>
  <%= f.label :content %>
  <%= f.text_field :content, class: 'form-control' %>
  <br>
  <%= f.label :status %>
  <%= f.select :status, [["下書き保存", "1"],["公開", "2"]] %>
  <br>
  <%= f.submit '作成', class: 'btn btn-primary btn-block' %>
<% end %>

app/views/blogs/draft.html.erb
<div class = "container">
  <div class = "wrapper col-md-8 col-md-offset-2 col-sm-10">
    <h1>下書き一覧</h1>
    <% @blog.each do |blog| %>
    <div class = "row">
      <p>タイトル:<%= blog.title %></p>
      <p>本文:<%= blog.content %></p>
      <%= link_to "編集", edit_blog_path(blog.id), class: 'btn btn-default btn-sm btn-success' %>
      <%= link_to "削除", blog_path(blog.id), method: :delete, data: { confirm: '本当に削除していいですか？'}, class: 'btn btn-default btn-sm btn btn-danger' %>
    </div>
    <% end %>
    <br><br>
    <%= link_to "ブログ一覧にもどる", blogs_path %>
  </div>
</div>

app/views/blogs/edit.html.erb
<div class = "container">
  <div class = "col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <h1>ブログ編集</h1>
    <%= render 'form' %>
    <%= link_to "もどる", :back %>
  </div>
</div>

app/views/blogs/index.html.erb
<div class = "container">
  <div class = "wrapper col-md-8 col-md-offset-2 col-sm-10">
    <h1>ブログ一覧</h1>
    <%= link_to "ブログを作成する", new_blog_path %>
    <% @blog.each do |blog| %>
    <div class = "row">
      <p>タイトル:<%= blog.title %></p>
      <p>本文:<%= blog.content %></p>
      <%= link_to "編集", edit_blog_path(blog.id), class: 'btn btn-default btn-sm btn-success' %>
      <%= link_to "削除", blog_path(blog.id), method: :delete, data: { confirm: '本当に削除していいですか？'}, class: 'btn btn-default btn-sm btn btn-danger' %>
    </div>
    <% end %>
    <br><br>
    <%= link_to "下書き一覧", '/draft' %>
    <br>
    <%= link_to "削除ブログ一覧", '/trash' %>
  </div>
</div>

app/views/blogs/new.html.erb
<div class = "container">
  <div class = "col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <h1>ブログ作成</h1>
    <%= render 'form' %>
    <%= link_to "もどる", :back %>
  </div>
</div>

app/views/blogs/trash.html.erb
<div class = "container">
  <div class = "wrapper col-md-8 col-md-offset-2 col-sm-10">
    <h1>削除ブログ一覧</h1>
    <% @blog.each do |blog| %>
    <div class = "row">
      <p>タイトル:<%= blog.title %></p>
      <p>本文:<%= blog.content %></p>
    </div>
    <% end %>

    <%= link_to "ブログ一覧にもどる", blogs_path %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dive17</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name = "viewport" content = "width = device-width, initial-scale = 1">
</head>
<body>

<%= yield %>

</body>
</html>